# Generated by Django 5.0.1 on 2024-02-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0003_category_product_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='product_favorit',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
