# Generated by Django 5.0.1 on 2024-01-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('discription', models.TextField()),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/')),
            ],
        ),
    ]
