# Generated by Django 5.0.1 on 2024-01-29 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
