# Generated by Django 5.0.1 on 2024-02-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_product_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quintity',
            field=models.IntegerField(default=1),
        ),
    ]
