# Generated by Django 5.0.1 on 2024-02-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_yourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
