# Generated by Django 5.0.1 on 2024-02-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_yourmodel_field1_alter_yourmodel_field2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='field1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='yourmodel',
            name='field2',
            field=models.IntegerField(),
        ),
    ]
