# Generated by Django 5.0.1 on 2024-02-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_yourmodel_field1_alter_yourmodel_field2'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='field3',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yourmodel',
            name='field2',
            field=models.IntegerField(default=1),
        ),
    ]
