# Generated by Django 5.0.1 on 2024-02-19 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_yourmodel_field3_alter_yourmodel_field2'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='field4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
