# Generated by Django 5.0.1 on 2024-02-20 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_yourmodel_field4'),
    ]

    operations = [
        migrations.CreateModel(
            name='yourmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('categoryss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
