# Generated by Django 5.0.1 on 2024-02-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_yourmodels_delete_yourmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='yourmodels',
            name='categoryss',
        ),
    ]
