# Generated by Django 5.0.1 on 2024-02-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_product_publish_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelNotices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageNotices', models.ImageField(upload_to='imageNotices/%y/%m/%d/')),
            ],
        ),
    ]
