# Generated by Django 5.0.1 on 2024-03-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_modelnotices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quintity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discription',
        ),
    ]
