# Generated by Django 5.0.1 on 2024-03-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_quintity_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shapeproduct',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='typeproduct',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
