# Generated by Django 5.0.1 on 2024-03-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_productheight_product_productlength_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=None, upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productheight',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productlength',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productwidth',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
