# Generated by Django 5.0.1 on 2024-03-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_rename_quantity_product_quantityproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productheight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productlength',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productwidth',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
