# Generated by Django 5.0.1 on 2024-02-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('product', '0003_category_product_categorys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_details',
            field=models.ManyToManyField(through='orders.OrderDetails', to='product.product'),
        ),
    ]
