# Generated by Django 5.0.1 on 2024-02-14 11:24

import creditcards.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderdetails_price_alter_order_order_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='creditCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', creditcards.models.CardNumberField(max_length=25)),
                ('cc_expiry', creditcards.models.CardExpiryField()),
                ('cc_code', creditcards.models.SecurityCodeField(max_length=4)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
