# Generated by Django 5.0.1 on 2024-02-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_joborderform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jobOrderForm',
        ),
    ]
