# Generated by Django 5.0.1 on 2024-02-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_joborderform'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborderform',
            name='proimg',
            field=models.ImageField(default='default_photo.jpg', upload_to='proimg/%Y/%m/%d/'),
        ),
    ]
