# Generated by Django 5.0.1 on 2024-02-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_joborderform_proimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborderform',
            name='pdffile',
            field=models.FileField(default='default.pdf', upload_to='uploads/pdffiles'),
        ),
    ]
