# Generated by Django 5.0.1 on 2024-02-27 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_product_order_items_count_order_jobordernumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='jobordernumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.joborderform'),
        ),
    ]
