# Generated by Django 5.0.1 on 2024-02-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_jobordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='jobordernumber',
            field=models.IntegerField(default=0),
        ),
    ]
