# Generated by Django 5.0.1 on 2024-02-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderdetails_product_remove_order_items_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborderform',
            name='pdffile',
            field=models.FileField(upload_to='uploads/pdffiles'),
        ),
        migrations.AlterField(
            model_name='joborderform',
            name='proimg',
            field=models.ImageField(upload_to='proimg/%Y/%m/%d/'),
        ),
    ]
