# Generated by Django 5.0.1 on 2024-02-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_joborderform_pdffile_alter_joborderform_proimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborderform',
            name='numberproject',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='joborderform',
            name='pdffile',
            field=models.FileField(upload_to='uploads/pdffiles/'),
        ),
        migrations.AlterField(
            model_name='joborderform',
            name='venueLocation',
            field=models.CharField(max_length=100),
        ),
    ]
