# Generated by Django 5.0.1 on 2024-02-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_order_order_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
