# Generated by Django 5.0.1 on 2024-03-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'Published'), ('d', 'Draft')], default='p', max_length=1),
            preserve_default=False,
        ),
    ]
